### ISSUE TITLE
Feature Request: Optional toned down halo texture

### ISSUE THREAD

**Issue by MuteTiefling** [shBLOCK/InteractiveCorporea#1]
Love the mod. This is a really cool concept and I really enjoy the fact that it consumes mana to use. 

I am, however, having some difficulty with the requesting halo triggering my motion sickness. 

Would you be willing to add a config option that would allow it to show a static image instead? Something similar to the botania halos?

![requesting_halo](https://user-images.githubusercontent.com/9543430/151591461-04e5a516-cc12-493c-a4f2-9f3847eff900.png)

**Comment by shBLOCK** [comment]
Thanks for the post!
I'm not too sure what you means, is it the random motion of the items or you constainly rotating around to find items or something else?

**Comment by MuteTiefling** [comment]
Just the actual halo item. The constant motion of our in my hotbar is a bit rough on me.

**Comment by shBLOCK** [comment]
Oh, that would be easy, it would become a config option in the next update

**Comment by MuteTiefling** [comment]
Awesome! Thanks <3

**Comment by shBLOCK** [comment]
Config option added in version 1.2
https://www.curseforge.com/minecraft/mc-mods/interactive-corporea/files/3627380
