### ISSUE TITLE
Quantization Device doesn't drop itself when mined

### ISSUE THREAD

**Issue by tweakbsd** [shBLOCK/InteractiveCorporea#2]
If I place down the device block I cannot mine it again. It doesn't drop anything, even with silk touch it's gone.
Not sure if it is intended behaviour for such an expensive block to be gone after mining.

**Comment by shBLOCK** [comment]
Oh sorry, I forgot to add the loot table for that...
Thanks for the report.
You can cheat that back in because that's definally a bug😄

**Comment by shBLOCK** [comment]
Fixed in 1.4

**Comment by tweakbsd** [comment]
Yeah I've added the missing loot table in my fork just right now. But you were faster so I guess it's useless doing a pull request if 1.4 comes out soon. Thanks nevertheless.

**Comment by shBLOCK** [comment]
That's true, but thank you anyways!
